### ISSUE TITLE
Please provide license info

### ISSUE THREAD

**Issue by AnthonyAkentiev** [ipfs-elastic-provider/ipfs-elastic-provider#7]
Hello.

I am planning to use and test the "Elastic IPFS" approach. License would be a great additional information.
Is it GPL or MIT (just an example)?

Thank you.

**Comment by francardoso93** [comment]
Hey @AnthonyAkentiev, thank you for pointing this out!
I've added the `Permissive License Stack` to all Elastic IPFS repos.

**Comment by AnthonyAkentiev** [comment]
@francardoso93 thx!
